# Generated by Django 5.1.2 on 2025-01-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight_v2',
            name='id',
        ),
        migrations.AlterField(
            model_name='weight_v2',
            name='asgn_cd',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
