# Generated by Django 5.1.2 on 2025-01-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_remove_weight_v2_id_alter_weight_v2_asgn_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_v2',
            name='asgn_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.weight_v2'),
        ),
    ]
