# Generated by Django 5.1.2 on 2025-01-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_alter_user_v2_asgn_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_v2',
            name='company',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='user_v2',
            name='depart',
            field=models.CharField(default='Unknown', max_length=25),
        ),
    ]
