# Generated by Django 5.1.2 on 2025-02-12 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0004_user_v2_company_user_v2_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight_v3',
            fields=[
                ('asgn_cd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=25)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_v3',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('depart', models.CharField(default='Unknown', max_length=25)),
                ('company', models.CharField(default='Unknown', max_length=25)),
                ('asgn_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.weight_v2')),
            ],
        ),
    ]
