# Generated by Django 5.1.2 on 2025-02-12 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0005_weight_v3_user_v3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_v3',
            name='asgn_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.weight_v3'),
        ),
    ]
