# Generated by Django 5.1.2 on 2025-02-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0006_alter_user_v3_asgn_cd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='user_v2',
            name='asgn_cd',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.DeleteModel(
            name='User_v2',
        ),
        migrations.DeleteModel(
            name='Weight_v2',
        ),
    ]
