# Generated by Django 5.1.2 on 2025-02-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0007_delete_user_remove_user_v2_asgn_cd_delete_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight_v3',
            name='asgn_cd',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
